feat(secure): Add Malware, Drift, ML and AWS ML policy resources (#476)
* refactor: Add common schema

* feat: Add composite policy resource

* feat: Add composite policy data source

* docs: Add docs for composite policy resource and data source

* chore: Fix formatting issues

* chore: Update TODO comments in composite policies client

* feat: Filter policies by type and name

* chore: Clean up code

* chore: Update the docs

* chore: Fix formatting issue

* chore: Fix Sprintf args in test code

* fix: Remove ability enable or disable individual rules

* chore: Fix lint issues

* refactor: Introduce reducer pattern

* refactor: Use a consistent way to get policy ID

* fix: Resolve copylock error

* refactor: Rename Composite to Malware policy

* chore: Fix Linter errors

* Fix: Resolve compilation error

* feat: Add Drift policy resource and data source

* test: Update Malware policy tests

* docs: Update Malware policy docs

* feat: Add ML policy

* fix: Ensure the version number is sent to Policies API in order to update resources

* chore: Update Drift policy docs

* fix: Resolve Lin issue

* feat: Add AWS ML policy

* chore: Fix docs typo

* fix: Add AWS ML policy to TF provider

* fix: Resolve "Setting state: Invalid address to set" error

* fix: Resolve compilation error

* fix: Skip version 0 to resolve resource update error

* fix: Resolve tfproviderdocs check error

* fix: Resolve "Invalid address to set" in drift policy resource

* fix: Fix resource_sysdig_secure_policy_test test failure

Error: expected [{pathStepImpl:{} Name:type}] to be one of [falco list_matching k8s_audit aws_cloudtrail gcp_auditlog azure_platformlogs okta github malware drift aws_machine_learning machine_learning], got awscloudtrail

* fix: Fix TestAccMalwarePolicy test failure

Error: Invalid argument name. Argument names must not be quoted.

* fix: Fix TestAccDriftPolicy test failure

* feat: Hide tags

* feat: Replace Drift rule Mode attribute with a boolean Enabled attribute

* fix: Fix Drift rule reducer

* fix: Hide Drift rule's match_items attribute

* fix: Fix "Invalid resource type" in TestAccMalwarePolicy test

* refactor: Remove details block and rename rules to rule

* fix: Fix "provide at least one rule name" test error

* docs: Update docs to include the latest TF resource changes

* test: Update tests

* chore: Update schema formatting

* fix: Escape query param

* refactor: Use const values

* tests: Generate unique policy name in data source tests

* tests: Add more tests to resources

* remove unnecessary changes

* more small fixes

* set hash alias field as optional

* remove hash alias references

---------

Co-authored-by: kmvachhani <krishna.vachhani@sysdig.com>
Co-authored-by: kmvachhani <63314936+kmvachhani@users.noreply.github.com>